(() => {
  "use strict";
  const X=globalThis.__XVS8;if(!X||X.controllerLoaded)return;X.controllerLoaded=true;const s=X.state;
  async function loadCurrent(dir,navId){if(navId!==s.navId)return false;const i=X.currentItem();if(!i)return false;if(i.type==="video"&&i.key&&(!i.el||!document.contains(i.el))){X.refind(i);if((!i.el||!document.contains(i.el))&&dir!==0){for(let n=0;n<6;n++){if(navId!==s.navId)return false;window.scrollBy({top:innerHeight*.7*dir,behavior:"smooth"});await X.sleep(400);X.refind(i);if(i.el&&document.contains(i.el))break;}}}if(navId!==s.navId)return false;const ok=i.type==="image"?await X.moveImage(i):await X.moveVideo(i);if(!ok)return false;if(i.type==="image")return true;X.playWithRetry(2);setTimeout(()=>{if(!s.player||s.manualPause||navId!==s.navId)return;const stalled=s.player.paused&&!s.player.ended&&s.player.currentTime<.1,noMeta=s.player.readyState<2||!Number.isFinite(s.player.duration);if((stalled||noMeta)&&s.player.networkState!==2){X.playWithRetry(1);setTimeout(()=>{if(!s.player||s.manualPause||navId!==s.navId)return;if(s.player.paused&&!s.player.ended&&s.player.currentTime<.1&&s.player.networkState!==2)void goTo(s.index+(dir>=0?1:-1));},2000);}},4000);return true;}
  async function goTo(target){const navId=++s.navId,dir=target>s.index?1:target<s.index?-1:0;s.lastDir=dir;if(target<0)target=0;if(target>=s.items.length){const ok=await X.ensureIndex(target,navId);if(!ok||navId!==s.navId)return;}s.index=target;await loadCurrent(dir,navId);X.updateCounter();X.updateSocial();}
  function key(e){if(!s.overlay)return;if(e.code==="Escape"){e.preventDefault();destroyOverlay();}else if(["ArrowLeft","ArrowUp","PageUp"].includes(e.code)){e.preventDefault();void goTo(s.index-1);}else if(["ArrowRight","ArrowDown","PageDown"].includes(e.code)){e.preventDefault();void goTo(s.index+1);}else if(e.code==="Space"){e.preventDefault();s.overlay.querySelector("#xvs-play")?.click();}}
  function wheel(e){if(!s.overlay)return;if(e.target instanceof HTMLElement&&e.target.closest("button,input,select"))return;e.preventDefault();e.stopImmediatePropagation();const now=performance.now();if(now<s.wheelLockedUntil)return;s.wheelDelta+=e.deltaY;if(Math.abs(s.wheelDelta)<80)return;const d=s.wheelDelta>0?1:-1;s.wheelDelta=0;s.wheelLockedUntil=now+450;void goTo(s.index+d);}
  function bindInputs(){document.addEventListener("keydown",key,true);window.addEventListener("wheel",wheel,{capture:true,passive:false});}
  function unbindInputs(){document.removeEventListener("keydown",key,true);window.removeEventListener("wheel",wheel,true);}
  function destroyOverlay(){if(!s.overlay)return;++s.navId;unbindInputs();clearInterval(s.socialTimer);s.socialTimer=null;X.clearImageTimers();X.detachPlayerEvents();try{X.restoreActive();}catch{}s.overlay.remove();s.overlay=s.host=s.player=null;s.items=[];s.index=0;s.manualPause=false;s.active=false;X.resetSeen();X.stopObserver();}
  function start(options={}){if(s.active&&s.overlay)return{ok:true,active:true,message:`Slideshow already running with ${s.items.length} item${s.items.length===1?"":"s"}.`};s.active=true;s.items=[];s.index=0;X.resetSeen();s.includeImages=Boolean(options.includeImages);const sec=Number(options.imageIntervalSeconds)||3;s.imageIntervalMs=Math.min(30000,Math.max(1000,sec*1000));s.muted=true;s.volume=.5;X.collectMedia();X.startObserver();if(!s.items.length){(async()=>{const id=++s.navId;for(let n=0;n<3&&!s.items.length;n++){await X.attemptLoadMore(n,id);X.collectMedia();}if(id!==s.navId)return;if(!s.items.length){s.active=false;X.stopObserver();alert(s.includeImages?"No videos or images found on this part of the page.":"No videos found on this part of the page.");return;}X.createOverlay();s.index=0;await loadCurrent(0,id);})();return{ok:false,active:true,message:s.includeImages?"Looking for videos and images…":"Looking for videos…"};}X.createOverlay();const id=++s.navId;void loadCurrent(0,id);return{ok:true,active:true,message:`Starting with ${s.items.length} item${s.items.length===1?"":"s"}.`};}
  Object.assign(X,{goTo,destroyOverlay,bindInputs});
  browser.runtime.onMessage.addListener(msg=>{if(msg?.type==="XVS_PING"||msg?.type==="TWITTER_SLIDESHOW_STATUS")return Promise.resolve({loaded:true,ok:true,active:s.active&&Boolean(s.overlay),itemCount:s.items.length,currentIndex:s.index,includeImages:s.includeImages,imageIntervalSeconds:Math.round(s.imageIntervalMs/1000),architecture:"chrome-v3-full-feature-port"});if(msg?.type==="STOP_TWITTER_SLIDESHOW"){if(s.overlay)destroyOverlay();else{s.active=false;X.stopObserver();}return Promise.resolve({ok:true,active:false,message:"Slideshow stopped."});}if(msg?.type==="START_TWITTER_SLIDESHOW")return Promise.resolve(start({includeImages:msg.includeImages,imageIntervalSeconds:msg.imageIntervalSeconds}));if(msg?.type==="XVS_TOGGLE"){if(s.active){if(s.overlay)destroyOverlay();else s.active=false;return Promise.resolve({ok:true,active:false});}return Promise.resolve(start());}return undefined;});
})();