(() => {
  "use strict";
  if (globalThis.__XVS8) return;
  const OVERLAY_ID="twitter-video-slideshow-overlay";
  const state={overlay:null,host:null,player:null,items:[],index:0,active:false,manualPause:false,activeVideo:null,navId:0,lastDir:0,muted:true,volume:.5,rate:1,observer:null,collectTimer:null,seenVideoKeys:new Set(),seenImageKeys:new Set(),seenVideoEls:new WeakSet(),seenImageEls:new WeakSet(),seenArticles:new WeakSet(),includeImages:false,imageIntervalMs:3000,imageTimer:null,imageProgressTimer:null,imageStartedAt:0,imageRunMs:0,imageRemainingMs:0,wheelDelta:0,wheelLockedUntil:0,socialTimer:null};
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const currentItem=()=>state.items[state.index]||null;
  function sourceOf(v){return v.currentSrc||v.src||Array.from(v.querySelectorAll("source")).find(s=>s.src)?.src||null;}
  function tweetKey(a,src){let k=a?.querySelector('a[href*="/status/"]')?.href?.split("?")[0]||a?.dataset?.xvsKey||src||null;if(a?.dataset&&k)a.dataset.xvsKey=k;return k;}
  function normalizeImage(src){if(!src)return null;try{const u=new URL(src);if(!u.hostname.endsWith("twimg.com")||!u.pathname.includes("/media/"))return null;u.searchParams.set("name","large");return u.toString();}catch{return null;}}
  function imageKey(a,src){const status=a?.querySelector('a[href*="/status/"]')?.href?.split("?")[0]||"image";let clean=src;try{const u=new URL(src);clean=`${u.origin}${u.pathname}`;}catch{}return `${status}::${clean}`;}
  function updateCount(){globalThis.__XVS8?.updateCounter?.();}
  function collectVideos(){let n=0;for(const el of document.querySelectorAll("video")){if(el.closest(`#${OVERLAY_ID}`))continue;const a=el.closest("article");if(!a||state.seenVideoEls.has(el)||state.seenArticles.has(a))continue;let src=sourceOf(el)||a.querySelector('source[src*="video.twimg.com"]')?.src||a.querySelector('a[href*="video.twimg.com"]')?.href||null;if(!src&&el.readyState<2)continue;if(!src)continue;const d=Number.isFinite(el.duration)&&el.duration>0?el.duration:null;if(!d)continue;const k=tweetKey(a,src);if(k&&state.seenVideoKeys.has(k))continue;if(k)state.seenVideoKeys.add(k);state.seenVideoEls.add(el);state.seenArticles.add(a);state.items.push({type:"video",el,src,duration:d,key:k,placeholder:null,originalParent:null});n++;}updateCount();return n;}
  function collectImages(){if(!state.includeImages)return 0;let n=0;for(const el of document.querySelectorAll('article img[src*="twimg.com/media/"]')){if(el.closest(`#${OVERLAY_ID}`)||state.seenImageEls.has(el))continue;const a=el.closest("article");if(!a)continue;const src=normalizeImage(el.currentSrc||el.src);if(!src)continue;const k=imageKey(a,src);if(state.seenImageKeys.has(k))continue;state.seenImageKeys.add(k);state.seenImageEls.add(el);state.items.push({type:"image",el,src,duration:state.imageIntervalMs/1000,key:k,placeholder:null,originalParent:null});n++;}updateCount();return n;}
  const collectMedia=()=>collectVideos()+collectImages();
  function startObserver(){if(state.observer)return;state.observer=new MutationObserver(()=>{clearTimeout(state.collectTimer);state.collectTimer=setTimeout(()=>{if(state.active)collectMedia();state.collectTimer=null;},2500);});state.observer.observe(document.body,{childList:true,subtree:true});}
  function stopObserver(){clearTimeout(state.collectTimer);state.collectTimer=null;state.observer?.disconnect();state.observer=null;}
  function scrollNode(i){if(!i)return null;if(i.el&&document.contains(i.el))return i.el;if(i.placeholder&&document.contains(i.placeholder))return i.placeholder;return null;}
  async function attemptLoadMore(tries=0,navId){if(!state.active||(navId&&navId!==state.navId))return false;const before=state.items.length,node=scrollNode(state.items.at(-1));if(node){try{node.scrollIntoView({behavior:"smooth",block:"center"});}catch{}await sleep(200);}if(state.player&&!state.player.paused&&!state.player.ended&&tries<2)return false;for(let i=0;i<3;i++){if(!state.active||(navId&&navId!==state.navId))return false;window.scrollBy({top:innerHeight*.9,behavior:"smooth"});await sleep(220+i*80);}await sleep(500+tries*150);if(!state.active||(navId&&navId!==state.navId))return false;collectMedia();return state.items.length>before;}
  async function ensureIndex(index,navId){let tries=0;while(index>=state.items.length&&tries<5){const loaded=await attemptLoadMore(tries,navId);tries++;if(!loaded){await sleep(500);if(!state.active||navId!==state.navId)return false;collectMedia();}}return index<state.items.length;}
  function refind(item){if(!item?.key||item.type!=="video")return false;for(const a of document.querySelectorAll("article")){const k=a.querySelector('a[href*="/status/"]')?.href?.split("?")[0]||a.dataset?.xvsKey||null;if(k!==item.key)continue;const v=a.querySelector("video");if(v){item.el=v;state.seenVideoEls.add(v);state.seenArticles.add(a);return true;}}return false;}
  function resetSeen(){state.seenVideoKeys.clear();state.seenImageKeys.clear();state.seenVideoEls=new WeakSet();state.seenImageEls=new WeakSet();state.seenArticles=new WeakSet();}
  globalThis.__XVS8={OVERLAY_ID,state,sleep,currentItem,collectMedia,startObserver,stopObserver,attemptLoadMore,ensureIndex,refind,resetSeen};
})();