(() => {
  "use strict";
  const X=globalThis.__XVS8;if(!X||X.playerLoaded)return;X.playerLoaded=true;const s=X.state;
  function restoreActive(){const a=s.activeVideo;if(!a)return;try{if(a.placeholder?.isConnected&&a.originalParent?.isConnected){a.originalParent.insertBefore(a.el,a.placeholder);a.placeholder.remove();}}catch{}s.activeVideo=null;}
  function detach(){const p=s.player;if(!p)return;p.removeEventListener("ended",onEnded);p.removeEventListener("pause",onPause);p.removeEventListener("timeupdate",updateProgress);p.removeEventListener("loadedmetadata",updateProgress);p.removeEventListener("canplay",updateProgress);}
  function clearImageTimers(){clearTimeout(s.imageTimer);clearInterval(s.imageProgressTimer);s.imageTimer=s.imageProgressTimer=null;s.imageStartedAt=s.imageRunMs=0;}
  function applyVolume(){if(!s.player)return;const m=s.muted||s.volume<=0;s.player.muted=m;s.player.volume=m?0:s.volume;const b=s.overlay?.querySelector("#xvs-mute");if(b)b.textContent=m?"Muted":"Sound";}
  function playWithRetry(n=2){const p=s.player;if(!p||!p.paused||p.seeking)return;applyVolume();const r=p.play();if(r?.catch)r.catch(e=>{if(n>0)setTimeout(()=>playWithRetry(n-1),100);else console.warn("XVS autoplay failed",e);});}
  function onEnded(){if(!s.manualPause&&s.active)void X.goTo?.(s.index+1);}
  function onPause(){if(!s.player||s.manualPause||s.player.ended)return;playWithRetry(1);}
  const fmt=v=>Number.isFinite(v)?`${Math.floor(v/60)}:${String(Math.floor(v%60)).padStart(2,"0")}`:"--:--";
  function updateCounter(){const e=s.overlay?.querySelector("#xvs-count");if(e)e.textContent=`${Math.min(s.index+1,s.items.length)}/${s.items.length||"--"}`;}
  function updateProgress(){const r=s.overlay?.querySelector("#xvs-progress"),t=s.overlay?.querySelector("#xvs-time"),item=X.currentItem();if(item?.type==="image"){const total=s.imageIntervalMs||3000,rem=Math.max(0,s.imageRemainingMs),pct=total?1-rem/total:0;if(r)r.value=String(Math.round(pct*1000));if(t)t.textContent=`${fmt((total-rem)/1000)} / ${fmt(total/1000)}`;updateCounter();return;}const p=s.player;if(!p)return;if(r)r.value=Number.isFinite(p.duration)&&p.duration>0?String(Math.round(p.currentTime/p.duration*1000)):"0";if(t)t.textContent=`${fmt(p.currentTime)} / ${fmt(p.duration)}`;updateCounter();}
  function startImageAdvance(ms=s.imageIntervalMs){clearImageTimers();s.imageRemainingMs=Math.max(0,ms);s.imageStartedAt=Date.now();s.imageRunMs=s.imageRemainingMs;s.imageProgressTimer=setInterval(()=>{if(s.manualPause||X.currentItem()?.type!=="image")return;s.imageRemainingMs=Math.max(0,s.imageRunMs-(Date.now()-s.imageStartedAt));updateProgress();},100);s.imageTimer=setTimeout(()=>{if(!s.manualPause&&X.currentItem()?.type==="image")void X.goTo?.(s.index+1);},s.imageRemainingMs);}
  function pauseImage(){if(X.currentItem()?.type!=="image")return;s.imageRemainingMs=Math.max(0,s.imageRunMs-(Date.now()-s.imageStartedAt));clearImageTimers();updateProgress();}
  function currentArticle(){const i=X.currentItem();if(!i)return null;if(i.type==="video"&&s.activeVideo?.el===i.el)return s.activeVideo.originalParent?.closest("article")||null;return i.el?.closest?.("article")||i.originalParent?.closest?.("article")||null;}
  function updateSocial(){const a=currentArticle(),like=s.overlay?.querySelector("#xvs-like"),rt=s.overlay?.querySelector("#xvs-retweet"),bk=s.overlay?.querySelector("#xvs-bookmark");if(!a)return;const l=a.querySelector('[data-testid="like"],[data-testid="unlike"]');if(l&&like)like.classList.toggle("active",l.dataset.testid==="unlike"||l.getAttribute("data-testid")==="unlike");const rr=a.querySelector('[data-testid="retweet"],[data-testid="unretweet"]');if(rr&&rt)rt.classList.toggle("active",rr.getAttribute("data-testid")==="unretweet");const b=a.querySelector('[data-testid="bookmark"],[data-testid="removeBookmark"]');if(b&&bk)bk.classList.toggle("active",b.getAttribute("data-testid")==="removeBookmark");}
  function proxySocial(k){const a=currentArticle();if(!a)return;const sel={like:'[data-testid="like"],[data-testid="unlike"]',retweet:'[data-testid="retweet"],[data-testid="unretweet"]',bookmark:'[data-testid="bookmark"],[data-testid="removeBookmark"]'}[k],b=a.querySelector(sel);if(!b)return;b.click();if(k==="retweet")setTimeout(()=>document.querySelector('[data-testid="retweetConfirm"]')?.click(),150);setTimeout(updateSocial,220);}
  function html(){return `<div id="xvs-host"></div><button id="xvs-close">×</button><div id="xvs-social"><button id="xvs-like" title="Like">♥</button><button id="xvs-retweet" title="Repost">↻</button><button id="xvs-bookmark" title="Bookmark">🔖</button></div><div id="xvs-controls"><button id="xvs-prev">◀</button><button id="xvs-play">Pause</button><button id="xvs-next">▶</button><input id="xvs-progress" type="range" min="0" max="1000" value="0"><span id="xvs-time">0:00 / 0:00</span><button id="xvs-mute">Muted</button><input id="xvs-volume" type="range" min="0" max="1" step="0.05" value="0"><select id="xvs-rate"><option>.5x</option><option>.75x</option><option selected>1x</option><option>1.25x</option><option>1.5x</option><option>2x</option></select><span id="xvs-count">--/--</span></div>`;}
  function createOverlay(){if(s.overlay)return;const o=document.createElement("div");o.id=X.OVERLAY_ID;o.innerHTML=html();const st=document.createElement("style");st.textContent=`#${X.OVERLAY_ID} #xvs-host video,#${X.OVERLAY_ID} #xvs-host img{width:100%!important;height:100%!important;max-width:100%!important;max-height:100%!important;object-fit:contain!important;background:#000!important;display:block!important}#${X.OVERLAY_ID} #xvs-social button.active{color:#1d9bf0!important;background:rgba(29,155,240,.18)!important}`;o.appendChild(st);Object.assign(o.style,{position:"fixed",inset:"0",zIndex:"999999",background:"rgba(0,0,0,.96)",color:"#fff"});const host=o.querySelector("#xvs-host");Object.assign(host.style,{position:"absolute",inset:"0 0 58px 0",display:"flex",alignItems:"center",justifyContent:"center",overflow:"hidden"});const c=o.querySelector("#xvs-controls");Object.assign(c.style,{position:"absolute",left:"0",right:"0",bottom:"0",height:"58px",display:"grid",gridTemplateColumns:"auto auto auto 1fr auto auto 90px auto auto",alignItems:"center",gap:"8px",padding:"6px 14px",boxSizing:"border-box",background:"rgba(0,0,0,.86)"});Object.assign(o.querySelector("#xvs-social").style,{position:"absolute",right:"18px",bottom:"72px",zIndex:"12",display:"flex",gap:"8px"});o.querySelectorAll("button,select").forEach(e=>Object.assign(e.style,{background:"#202327",color:"#fff",border:"0",borderRadius:"8px",padding:"8px",cursor:"pointer"}));Object.assign(o.querySelector("#xvs-close").style,{position:"absolute",top:"12px",right:"12px",zIndex:"10",width:"34px",height:"34px"});document.body.appendChild(o);s.overlay=o;s.host=host;
    o.querySelector("#xvs-close").onclick=()=>X.destroyOverlay?.();o.querySelector("#xvs-prev").onclick=()=>void X.goTo?.(s.index-1);o.querySelector("#xvs-next").onclick=()=>void X.goTo?.(s.index+1);
    o.querySelector("#xvs-play").onclick=()=>{const i=X.currentItem();if(i?.type==="image"){if(s.manualPause){s.manualPause=false;startImageAdvance(s.imageRemainingMs||s.imageIntervalMs);}else{s.manualPause=true;pauseImage();}o.querySelector("#xvs-play").textContent=s.manualPause?"Play":"Pause";return;}const p=s.player;if(!p)return;if(p.paused){s.manualPause=false;playWithRetry(2);}else{s.manualPause=true;p.pause();}o.querySelector("#xvs-play").textContent=p.paused?"Play":"Pause";};
    o.querySelector("#xvs-mute").onclick=()=>{s.muted=!s.muted;if(!s.muted&&s.volume<=0)s.volume=.5;o.querySelector("#xvs-volume").value=s.muted?"0":String(s.volume);applyVolume();};o.querySelector("#xvs-volume").oninput=e=>{s.volume=Math.max(0,Math.min(1,Number(e.target.value)||0));s.muted=s.volume===0;applyVolume();};
    o.querySelector("#xvs-progress").oninput=e=>{const i=X.currentItem();if(i?.type==="image"){const pct=Number(e.target.value)/1000;s.imageRemainingMs=s.imageIntervalMs-Math.max(0,Math.min(1,pct))*s.imageIntervalMs;if(!s.manualPause)startImageAdvance(s.imageRemainingMs);else updateProgress();return;}const p=s.player;if(p&&Number.isFinite(p.duration)&&p.duration>0)p.currentTime=Number(e.target.value)/1000*p.duration;};
    o.querySelector("#xvs-rate").onchange=e=>{const m={".5x":.5,".75x":.75,"1x":1,"1.25x":1.25,"1.5x":1.5,"2x":2};s.rate=m[e.target.value]||1;if(s.player)s.player.playbackRate=s.rate;};o.querySelector("#xvs-like").onclick=()=>proxySocial("like");o.querySelector("#xvs-retweet").onclick=()=>proxySocial("retweet");o.querySelector("#xvs-bookmark").onclick=()=>proxySocial("bookmark");s.socialTimer=setInterval(updateSocial,1000);X.bindInputs?.();}
  async function moveVideo(i){const el=i?.el;if(!(el instanceof HTMLVideoElement)||!el.isConnected)return false;clearImageTimers();detach();try{s.player?.pause();}catch{}restoreActive();const p=el.parentElement;if(!p)return false;const ph=document.createElement("div");ph.style.display="none";p.insertBefore(ph,el);s.activeVideo={el,placeholder:ph,originalParent:p};i.placeholder=ph;i.originalParent=p;s.player=el;s.host.innerHTML="";s.host.appendChild(el);el.controls=false;el.playsInline=true;el.loop=false;el.playbackRate=s.rate;applyVolume();el.addEventListener("ended",onEnded);el.addEventListener("pause",onPause);el.addEventListener("timeupdate",updateProgress);el.addEventListener("loadedmetadata",updateProgress);el.addEventListener("canplay",updateProgress);if(el.currentTime>.5)try{el.currentTime=0;}catch{}s.manualPause=false;playWithRetry(3);updateProgress();updateSocial();setTimeout(()=>{if(s.player&&!s.player.ended&&!s.manualPause&&s.player.paused)playWithRetry(1);},400);return true;}
  async function moveImage(i){clearImageTimers();detach();try{s.player?.pause();}catch{}s.player=null;restoreActive();if(!i?.src)return false;const img=document.createElement("img");img.src=i.src;img.alt="Tweet image";img.draggable=false;img.onclick=()=>s.overlay?.querySelector("#xvs-play")?.click();s.host.innerHTML="";s.host.appendChild(img);s.imageRemainingMs=s.imageIntervalMs;s.manualPause=false;s.overlay.querySelector("#xvs-play").textContent="Pause";updateProgress();updateSocial();startImageAdvance(s.imageIntervalMs);return true;}
  Object.assign(X,{restoreActive,detachPlayerEvents:detach,clearImageTimers,applyVolume,playWithRetry,updateCounter,updateProgress,updateSocial,createOverlay,moveVideo,moveImage});
})();